import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import dynamic from 'next/dynamic'

import Head from "next/head";
import "../styles/globals.css";
import Layout from "../components/Layout";


function MyApp({ Component, pageProps }) {

  const router = useRouter();
  const [isAuthenticated, setIsAuthenticated] = useState(false);

  useEffect(() => {
    const authToken = sessionStorage.getItem('accessToken');
    console.log("authToken",authToken)
    if (authToken) {
      setIsAuthenticated(true);
    } else {
      setIsAuthenticated(false);
    }
  }, []);

  // useEffect(() => {
  //   if (!isAuthenticated  || router.pathname === "/admin-dashboard") {
  //     router.replace("/admin-login");
  //     console.log("")
  //   }
  //   else{
  //     router.replace("/admin-dashboard");
  //   }
  // }, [isAuthenticated, router.pathname]);


  return (

    <>
      <Head>
        <title>Ecommerce-website</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700&family=Urbanist:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>

  );
}

export default MyApp;
